on: [push]
name: NEW_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -f ./counting-service/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/counting-service:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/counting-service:${{ github.sha }}
            docker build . -f ./dashboard-service/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/dashboard-service:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dashboard-service:${{ github.sha }}
        - uses: azure/aks-set-context@v1
          with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            cluster-name: Azure subscription 1
            resource-group: 1valResourceGroup
        - uses: azure/k8s-create-secret@v1
          with:
            container-registry-url: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
            container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            secret-name: application-secret-name
            namespace: val-ingress 
            force: true           


        - name: 'Deploy dashboard-service'
          uses: 'azure/k8s-deploy@v1'
          with:
            #resource-group: ${{ secrets.RESOURCE_GROUP }}
            #dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/dashboard-service:${{ github.sha }}
            #registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            #registry-username: ${{ secrets.REGISTRY_USERNAME }}
            #registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            #name: dep-dashboard-service
            #location: 'west us'
            manifests: dashboard-service/deployment.yaml
            imagepullsecrets: application-secret-name
            namespace: val-ingress
            
        - name: 'Deploy counting-service'
          uses: 'azure/k8s-deploy@v1'
          with:
            #resource-group: ${{ secrets.RESOURCE_GROUP }}
            #dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/counting-service:${{ github.sha }}
            #registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            #registry-username: ${{ secrets.REGISTRY_USERNAME }}
            #registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            #name: dep-counting-service
            #location: 'west us'
            manifests: counting-service/deployment.yaml
            imagepullsecrets: application-secret-name
            namespace: val-ingress    
            
